packages:
  - apps/*
  - packages/*

catalog:
  "@effect/sql-d1": 4.0.0-rc.112
  "@effect/sql-sqlite-do": 4.0.0-rc.112
  "@effect/vitest": 4.0.0-rc.112
  alchemy: 2.0.0-beta.74
  drizzle-kit: 1.0.0-rc.5-ab785fc
  drizzle-orm: 1.0.0-rc.5-ab785fc
  effect: 4.0.0-rc.112
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9

overrides:
  "@cloudflare/workers-types": 5.20260827.1
  "@effect/platform-node-shared": 4.0.0-rc.112
  "@effect/sql-d1": 4.0.0-rc.112
  "@effect/sql-sqlite-do": 4.0.0-rc.112
  drizzle-orm: 1.0.0-rc.5-ab785fc
  uuid: 11.1.1
  valibot: 1.4.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vitest: 4.1.11

onlyBuiltDependencies:
  - "@sentry/cli"
  - better-sqlite3
  - electron
  - esbuild
  - sharp
  - workerd

allowBuilds:
  "@firebase/util": false
  "@journeyapps/wa-sqlite": true
  "@sentry/cli": true
  better-sqlite3: true
  electron-winstaller: false
  esbuild: true
  msgpackr-extract: true
  protobufjs: false
  workerd: true

minimumReleaseAgeExclude:
  - "@tanstack/db@0.8.3"
  - "@tanstack/powersync-db-collection@0.1.62"
  - "@tanstack/react-db@0.3.3"
