import { defineConfig } from "vite-plus";

export default defineConfig({
  resolve: {
    tsconfigPaths: true,
  },
  fmt: {
    ignorePatterns: [
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".repos/**",
      ".roo/**",
      ".windsurf/**",
      "**/dist/**",
      "**/dist-electron/**",
      "**/.vite/**",
      "**/out/**",
      "**/release/**",
      "**/*.gen.ts",
      "**/worker-configuration.d.ts",
      "tools/oxlint/anti-slop/**",
    ],
    sortImports: true,
    sortTailwindcss: {
      functions: ["clsx", "cn", "cva", "twMerge"],
      stylesheet: "./apps/desktop/src/styles.css",
    },
  },
  staged: {
    "*": "vp check --fix",
  },
  test: {
    include: [
      "apps/*/test/**/*.test.{ts,tsx}",
      "packages/*/test/**/*.test.ts",
      "scripts/migrate-cloudflare/test/**/*.test.ts",
    ],
    setupFiles: ["./test/setup.ts"],
    testTimeout: 15_000,
  },
  lint: {
    ignorePatterns: [
      ".agent/**",
      ".agents/**",
      ".claude/**",
      ".codex/**",
      ".continue/**",
      ".cursor/**",
      ".gemini/**",
      ".opencode/**",
      ".pi/**",
      ".repos/**",
      ".roo/**",
      ".windsurf/**",
      "**/dist/**",
      "**/dist-electron/**",
      "**/.vite/**",
      "**/out/**",
      "**/release/**",
      "**/*.gen.ts",
      "**/worker-configuration.d.ts",
      "apps/server/workerd-proofs/**",
      "tools/oxlint/anti-slop/**",
    ],
    jsPlugins: [{ name: "anti-slop", specifier: "./tools/oxlint/anti-slop/index.ts" }],
    overrides: [
      {
        files: [
          "packages/sync/**/*.ts",
          "packages/client-db/src/replica/**/*.ts",
          "packages/client-db/test/replica-*.test.ts",
          "packages/contracts/src/sync/{api,directory,http-errors,live,protocol,snapshot}.ts",
          "apps/server/src/inventory/{inventory-directory,organization-host,organization-object,sync-authority}.ts",
          "apps/server/src/routes/{sync,sync-live}.ts",
          "apps/server/test/{http,inventory}/**/*.ts",
          "apps/server/test/infra/organization-object-planning.test.ts",
          "packages/contracts/src/sync/fixtures/**/*.ts",
          "packages/contracts/test/sync/**/*.ts",
          "apps/desktop/src/lib/inventory/{actions,index,open,provider,sync-status,types}.{ts,tsx}",
          "apps/desktop/src/lib/inventory-host.ts",
          "apps/desktop/src/start-electron.tsx",
          "apps/desktop/electron/inventory-http.ts",
          "apps/desktop/electron/inventory-http-channels.ts",
          "apps/desktop/test/electron/inventory-http.test.ts",
          "apps/desktop/test/inventory-workspace.test.ts",
          "scripts/migrate-cloudflare/**/*.ts",
        ],
        rules: {
          "anti-slop/no-comments": "error",
        },
      },
      {
        files: ["apps/desktop/src/**/*.{ts,tsx}"],
        plugins: ["react"],
        rules: {
          "react/no-children-prop": "off",
          // react/react-compiler was split into per-category rules in oxlint 1.79.
          "react/error-boundaries": "error",
          "react/globals": "error",
          "react/immutability": "error",
          "react/incompatible-library": "error",
          "react/preserve-manual-memoization": "error",
          "react/purity": "error",
          "react/refs": "error",
          "react/set-state-in-effect": "error",
          "react/set-state-in-render": "error",
          "react/static-components": "error",
          "react/use-memo": "error",
          "react/void-use-memo": "error",
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
    rules: {
      "anti-slop/no-chained-type-assertions": "error",
      "anti-slop/no-conditional-empty-object-spread": "error",
      "anti-slop/no-known-value-widening": "error",
      "anti-slop/no-module-mocking": "error",
      "anti-slop/no-object-parameters": "error",
      "anti-slop/no-reflect-apply": "error",
      "anti-slop/no-reflect-get": "error",
      "anti-slop/no-runtime-typeof": ["error", { allowInTypeGuards: true }],
      "anti-slop/no-shape-in-symbol-names": "error",
      "anti-slop/no-unknown-parameters": "error",
      "anti-slop/no-unknown-returns": "error",
      "anti-slop/no-unknown-type-aliases": "error",
      "anti-slop/no-unsafe-dictionary-type": "error",
      "anti-slop/no-widen-then-assert": "error",
      "anti-slop/require-safety-comment-for-type-assertion": "error",
    },
  },
});
