# yaml-language-server: $schema=https://unpkg.com/@powersync/cli-schemas@latest/json-schema/service-config.json
_type: cloud
name: Production
region: us

replication:
  connections:
    - type: postgresql
      hostname: us-east-2.pg.psdb.cloud
      port: 5432
      database: postgres
      username: pscale_api_7ycpdb2q2p25.xjdqadxfhv63
      password:
        secret: !env PS_DATABASE_PASSWORD
      name: Default
      tag: default
      sslmode: verify-full
      debug_api: false

client_auth:
  jwks_uri: https://auth.tabaaq.app/.well-known/jwks.json
  additional_audiences:
    - tabaaq-api
