const ANALYTICS_PERMANENT_STREAMS = 1;
const ANALYTICS_CONTROL_SLOTS = 4;
const ANALYTICS_FINITE_READS = 4;
export const ANALYTICS_WORKER_RPC_CONCURRENCY =
  ANALYTICS_PERMANENT_STREAMS + ANALYTICS_CONTROL_SLOTS + ANALYTICS_FINITE_READS;
