/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppInvoicesRouteImport } from './routes/_app/invoices'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPurchasesRouteImport } from './routes/_app/purchases'
import { Route as AppRestockRouteImport } from './routes/_app/restock'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppInvoicesInvoiceIdRouteImport } from './routes/_app/invoices/$invoiceId'
import { Route as AppInvoicesNewRouteImport } from './routes/_app/invoices/new'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsProductIdRouteImport } from './routes/_app/products/$productId'
import { Route as AppProductsCategoriesRouteImport } from './routes/_app/products/categories'
import { Route as AppProductsNewRouteImport } from './routes/_app/products/new'
import { Route as AppProductsUploadRouteImport } from './routes/_app/products/upload'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app/purchases/index'
import { Route as AppPurchasesOrderIdRouteImport } from './routes/_app/purchases/$orderId'
import { Route as AppPurchasesSuppliersRouteImport } from './routes/_app/purchases/suppliers'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsSectionRouteImport } from './routes/_app/settings/$section'
import { Route as AppProductsProductIdEditRouteImport } from './routes/_app/products/$productId_.edit'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppRestockRoute = AppRestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesInvoiceIdRoute = AppInvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppInvoicesRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsProductIdRoute = AppProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsCategoriesRoute = AppProductsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppProductsUploadRoute = AppProductsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppPurchasesOrderIdRoute = AppPurchasesOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppPurchasesSuppliersRoute = AppPurchasesSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppPurchasesRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsSectionRoute = AppSettingsSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppProductsProductIdEditRoute =
  AppProductsProductIdEditRouteImport.update({
    id: '/$productId_/edit',
    path: '/$productId/edit',
    getParentRoute: () => AppProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/$': typeof AppSplatRoute
  '/invoices': typeof AppInvoicesRouteWithChildren
  '/products': typeof AppProductsRouteWithChildren
  '/purchases': typeof AppPurchasesRouteWithChildren
  '/restock': typeof AppRestockRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/upload': typeof AppProductsUploadRoute
  '/purchases/$orderId': typeof AppPurchasesOrderIdRoute
  '/purchases/suppliers': typeof AppPurchasesSuppliersRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/$': typeof AppSplatRoute
  '/restock': typeof AppRestockRoute
  '/': typeof AppIndexRoute
  '/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/products/$productId': typeof AppProductsProductIdRoute
  '/products/categories': typeof AppProductsCategoriesRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/upload': typeof AppProductsUploadRoute
  '/purchases/$orderId': typeof AppPurchasesOrderIdRoute
  '/purchases/suppliers': typeof AppPurchasesSuppliersRoute
  '/settings/$section': typeof AppSettingsSectionRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/products/$productId/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/invoices': typeof AppInvoicesRouteWithChildren
  '/_app/products': typeof AppProductsRouteWithChildren
  '/_app/purchases': typeof AppPurchasesRouteWithChildren
  '/_app/restock': typeof AppRestockRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/invoices/$invoiceId': typeof AppInvoicesInvoiceIdRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/products/$productId': typeof AppProductsProductIdRoute
  '/_app/products/categories': typeof AppProductsCategoriesRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/products/upload': typeof AppProductsUploadRoute
  '/_app/purchases/$orderId': typeof AppPurchasesOrderIdRoute
  '/_app/purchases/suppliers': typeof AppPurchasesSuppliersRoute
  '/_app/settings/$section': typeof AppSettingsSectionRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/products/$productId_/edit': typeof AppProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/$'
    | '/invoices'
    | '/products'
    | '/purchases'
    | '/restock'
    | '/settings'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/products/$productId'
    | '/products/categories'
    | '/products/new'
    | '/products/upload'
    | '/purchases/$orderId'
    | '/purchases/suppliers'
    | '/settings/$section'
    | '/invoices/'
    | '/products/'
    | '/purchases/'
    | '/settings/'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/$'
    | '/restock'
    | '/'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/products/$productId'
    | '/products/categories'
    | '/products/new'
    | '/products/upload'
    | '/purchases/$orderId'
    | '/purchases/suppliers'
    | '/settings/$section'
    | '/invoices'
    | '/products'
    | '/purchases'
    | '/settings'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/$'
    | '/_app/invoices'
    | '/_app/products'
    | '/_app/purchases'
    | '/_app/restock'
    | '/_app/settings'
    | '/_app/'
    | '/_app/invoices/$invoiceId'
    | '/_app/invoices/new'
    | '/_app/products/$productId'
    | '/_app/products/categories'
    | '/_app/products/new'
    | '/_app/products/upload'
    | '/_app/purchases/$orderId'
    | '/_app/purchases/suppliers'
    | '/_app/settings/$section'
    | '/_app/invoices/'
    | '/_app/products/'
    | '/_app/purchases/'
    | '/_app/settings/'
    | '/_app/products/$productId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/restock': {
      id: '/_app/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof AppRestockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/$invoiceId': {
      id: '/_app/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof AppInvoicesInvoiceIdRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppInvoicesRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/$productId': {
      id: '/_app/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AppProductsProductIdRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/categories': {
      id: '/_app/products/categories'
      path: '/categories'
      fullPath: '/products/categories'
      preLoaderRoute: typeof AppProductsCategoriesRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/products/upload': {
      id: '/_app/products/upload'
      path: '/upload'
      fullPath: '/products/upload'
      preLoaderRoute: typeof AppProductsUploadRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/purchases/$orderId': {
      id: '/_app/purchases/$orderId'
      path: '/$orderId'
      fullPath: '/purchases/$orderId'
      preLoaderRoute: typeof AppPurchasesOrderIdRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/purchases/suppliers': {
      id: '/_app/purchases/suppliers'
      path: '/suppliers'
      fullPath: '/purchases/suppliers'
      preLoaderRoute: typeof AppPurchasesSuppliersRouteImport
      parentRoute: typeof AppPurchasesRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/$section': {
      id: '/_app/settings/$section'
      path: '/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof AppSettingsSectionRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/products/$productId_/edit': {
      id: '/_app/products/$productId_/edit'
      path: '/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof AppProductsProductIdEditRouteImport
      parentRoute: typeof AppProductsRoute
    }
  }
}

interface AppInvoicesRouteChildren {
  AppInvoicesInvoiceIdRoute: typeof AppInvoicesInvoiceIdRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
}

const AppInvoicesRouteChildren: AppInvoicesRouteChildren = {
  AppInvoicesInvoiceIdRoute: AppInvoicesInvoiceIdRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
}

const AppInvoicesRouteWithChildren = AppInvoicesRoute._addFileChildren(
  AppInvoicesRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsProductIdRoute: typeof AppProductsProductIdRoute
  AppProductsCategoriesRoute: typeof AppProductsCategoriesRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsUploadRoute: typeof AppProductsUploadRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsProductIdEditRoute: typeof AppProductsProductIdEditRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsProductIdRoute: AppProductsProductIdRoute,
  AppProductsCategoriesRoute: AppProductsCategoriesRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsUploadRoute: AppProductsUploadRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsProductIdEditRoute: AppProductsProductIdEditRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppPurchasesRouteChildren {
  AppPurchasesOrderIdRoute: typeof AppPurchasesOrderIdRoute
  AppPurchasesSuppliersRoute: typeof AppPurchasesSuppliersRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
}

const AppPurchasesRouteChildren: AppPurchasesRouteChildren = {
  AppPurchasesOrderIdRoute: AppPurchasesOrderIdRoute,
  AppPurchasesSuppliersRoute: AppPurchasesSuppliersRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
}

const AppPurchasesRouteWithChildren = AppPurchasesRoute._addFileChildren(
  AppPurchasesRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsSectionRoute: typeof AppSettingsSectionRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsSectionRoute: AppSettingsSectionRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppInvoicesRoute: typeof AppInvoicesRouteWithChildren
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppPurchasesRoute: typeof AppPurchasesRouteWithChildren
  AppRestockRoute: typeof AppRestockRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppInvoicesRoute: AppInvoicesRouteWithChildren,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppPurchasesRoute: AppPurchasesRouteWithChildren,
  AppRestockRoute: AppRestockRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
