/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices/$invoiceId'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'
import { Route as ProductsNewRouteImport } from './routes/products/new'
import { Route as ProductsUploadRouteImport } from './routes/products/upload'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as ProductsProductIdEditRouteImport } from './routes/products/$productId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsUploadRoute = ProductsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ProductsRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductsProductIdEditRoute = ProductsProductIdEditRouteImport.update({
  id: '/$productId_/edit',
  path: '/$productId/edit',
  getParentRoute: () => ProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/upload': typeof ProductsUploadRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/upload': typeof ProductsUploadRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/invoices': typeof InvoicesIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/products/$productId/edit': typeof ProductsProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/products/new': typeof ProductsNewRoute
  '/products/upload': typeof ProductsUploadRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/categories': typeof SettingsCategoriesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/products/$productId_/edit': typeof ProductsProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/invoices'
    | '/products'
    | '/settings'
    | '/sign-in'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/products/$productId'
    | '/products/new'
    | '/products/upload'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/categories'
    | '/settings/organization'
    | '/invoices/'
    | '/products/'
    | '/settings/'
    | '/products/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/products/$productId'
    | '/products/new'
    | '/products/upload'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/categories'
    | '/settings/organization'
    | '/invoices'
    | '/products'
    | '/settings'
    | '/products/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/invoices'
    | '/products'
    | '/settings'
    | '/sign-in'
    | '/invoices/$invoiceId'
    | '/invoices/new'
    | '/products/$productId'
    | '/products/new'
    | '/products/upload'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/categories'
    | '/settings/organization'
    | '/invoices/'
    | '/products/'
    | '/settings/'
    | '/products/$productId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/new': {
      id: '/products/new'
      path: '/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof ProductsNewRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/products/upload': {
      id: '/products/upload'
      path: '/upload'
      fullPath: '/products/upload'
      preLoaderRoute: typeof ProductsUploadRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/products/$productId_/edit': {
      id: '/products/$productId_/edit'
      path: '/$productId/edit'
      fullPath: '/products/$productId/edit'
      preLoaderRoute: typeof ProductsProductIdEditRouteImport
      parentRoute: typeof ProductsRoute
    }
  }
}

interface InvoicesRouteChildren {
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProductsNewRoute: typeof ProductsNewRoute
  ProductsUploadRoute: typeof ProductsUploadRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsProductIdEditRoute: typeof ProductsProductIdEditRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  ProductsUploadRoute: ProductsUploadRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsProductIdEditRoute: ProductsProductIdEditRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsCategoriesRoute: SettingsCategoriesRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
