import { createInsertSchema, createSelectSchema } from "drizzle-orm/effect-schema";
import { batches, categories, products } from "@store/database/schema";
import * as Schema from "effect/Schema";

// Wire schemas are derived from the drizzle tables so the database schema stays
// the single source of truth. `deletedAt` is a soft-delete storage detail and
// never crosses IPC; ids and timestamps are generated by the store, so create
// inputs omit them.

const productRow = createSelectSchema(products);
const productInsert = createInsertSchema(products);
const categoryRow = createSelectSchema(categories);

const { deletedAt: _categoryDeletedAt, ...categoryFields } = categoryRow.fields;
export const Category = Schema.Struct(categoryFields);
export type Category = typeof Category.Type;

const { deletedAt: _productDeletedAt, ...productFields } = productRow.fields;
export const Product = Schema.Struct({ ...productFields, category: Category });
export type Product = typeof Product.Type;

const {
  id: _productId,
  createdAt: _productCreatedAt,
  updatedAt: _productUpdatedAt,
  deletedAt: _productInsertDeletedAt,
  ...createProductFields
} = productInsert.fields;
export const CreateProductInput = Schema.Struct(createProductFields);
export type CreateProductInput = typeof CreateProductInput.Type;

export const UpdateProductInput = Schema.Struct({
  id: Schema.String,
  ...createProductFields,
});
export type UpdateProductInput = typeof UpdateProductInput.Type;

export const ProductIdInput = Schema.Struct({ id: Schema.String });
export type ProductIdInput = typeof ProductIdInput.Type;

const batchRow = createSelectSchema(batches);
const batchInsert = createInsertSchema(batches);

const { deletedAt: _batchDeletedAt, ...batchFields } = batchRow.fields;
export const Batch = Schema.Struct(batchFields);
export type Batch = typeof Batch.Type;

const {
  id: _batchId,
  createdAt: _batchCreatedAt,
  updatedAt: _batchUpdatedAt,
  deletedAt: _batchInsertDeletedAt,
  ...createBatchFields
} = batchInsert.fields;
export const CreateBatchInput = Schema.Struct(createBatchFields);
export type CreateBatchInput = typeof CreateBatchInput.Type;

export type SyncPhase = "local-only" | "idle" | "syncing" | "error";

export interface SyncStatus {
  readonly phase: SyncPhase;
  readonly configured: boolean;
  readonly lastSyncedAt: number | null;
  readonly message: string;
}

export interface OfflineStoreApi {
  readonly listCategories: () => Promise<ReadonlyArray<Category>>;
  readonly listProducts: () => Promise<ReadonlyArray<Product>>;
  readonly getProduct: (input: ProductIdInput) => Promise<Product>;
  readonly createProduct: (input: CreateProductInput) => Promise<Product>;
  readonly updateProduct: (input: UpdateProductInput) => Promise<Product>;
  readonly deleteProduct: (input: ProductIdInput) => Promise<void>;
  readonly getSyncStatus: () => Promise<SyncStatus>;
  readonly sync: () => Promise<SyncStatus>;
}
