import { createInsertSchema, createSelectSchema } from "drizzle-orm/effect-schema";
import {
  batches,
  categories,
  invoiceItems,
  invoices,
  products,
  stockMovements,
} from "@store/db/store.schema";
import * as Schema from "effect/Schema";

// Wire schemas are derived from the drizzle tables so the database schema stays
// the single source of truth. `deletedAt` is a soft-delete storage detail and
// never crosses IPC; ids and timestamps are generated by the store, so create
// inputs omit them.

const productRow = createSelectSchema(products);
const productInsert = createInsertSchema(products);
const categoryRow = createSelectSchema(categories);

const { deletedAt: _categoryDeletedAt, ...categoryFields } = categoryRow.fields;
export const Category = Schema.Struct(categoryFields);
export type Category = typeof Category.Type;

const batchRow = createSelectSchema(batches);
const batchInsert = createInsertSchema(batches);

const { deletedAt: _batchDeletedAt, ...batchFields } = batchRow.fields;
export const Batch = Schema.Struct(batchFields);
export type Batch = typeof Batch.Type;

const {
  id: _batchId,
  createdAt: _batchCreatedAt,
  updatedAt: _batchUpdatedAt,
  deletedAt: _batchInsertDeletedAt,
  organizationId: _batchOrganizationId,
  createdByUserId: _batchCreatedByUserId,
  updatedByUserId: _batchUpdatedByUserId,
  deviceId: _batchDeviceId,
  operationId: _batchOperationId,
  rowVersion: _batchRowVersion,
  ...createBatchFields
} = batchInsert.fields;
export const CreateBatchInput = Schema.Struct(createBatchFields);
export type CreateBatchInput = typeof CreateBatchInput.Type;

const { deletedAt: _productDeletedAt, ...productFields } = productRow.fields;
export const Product = Schema.Struct({
  ...productFields,
  category: Category,
  batches: Schema.Array(Batch),
});
export type Product = typeof Product.Type;

export const productPackStock = (product: Pick<Product, "batches">) =>
  product.batches.reduce((sum, batch) => sum + batch.packQuantity, 0);

export const productLooseUnitStock = (product: Pick<Product, "batches">) =>
  product.batches.reduce((sum, batch) => sum + batch.unitQuantity, 0);

export const productStock = (product: Pick<Product, "batches" | "unitsPerPack">) =>
  productPackStock(product) * product.unitsPerPack + productLooseUnitStock(product);

const {
  id: _productId,
  createdAt: _productCreatedAt,
  updatedAt: _productUpdatedAt,
  deletedAt: _productInsertDeletedAt,
  organizationId: _productOrganizationId,
  createdByUserId: _productCreatedByUserId,
  updatedByUserId: _productUpdatedByUserId,
  deviceId: _productDeviceId,
  operationId: _productOperationId,
  rowVersion: _productRowVersion,
  ...createProductFields
} = productInsert.fields;
export const CreateProductInput = Schema.Struct(createProductFields);
export type CreateProductInput = typeof CreateProductInput.Type;

export const UpdateProductInput = Schema.Struct({
  id: Schema.String,
  ...createProductFields,
});
export type UpdateProductInput = typeof UpdateProductInput.Type;

export const ProductIdInput = Schema.Struct({ id: Schema.String });
export type ProductIdInput = typeof ProductIdInput.Type;

export const SearchProductsInput = Schema.Struct({
  query: Schema.String,
  limit: Schema.optional(Schema.Number),
});
export type SearchProductsInput = typeof SearchProductsInput.Type;

const invoiceRow = createSelectSchema(invoices);
const invoiceItemRow = createSelectSchema(invoiceItems);

const { deletedAt: _invoiceItemDeletedAt, ...invoiceItemFields } = invoiceItemRow.fields;
export const InvoiceItem = Schema.Struct(invoiceItemFields);
export type InvoiceItem = typeof InvoiceItem.Type;

const { deletedAt: _invoiceDeletedAt, ...invoiceFields } = invoiceRow.fields;
export const Invoice = Schema.Struct({ ...invoiceFields, items: Schema.Array(InvoiceItem) });
export type Invoice = typeof Invoice.Type;

export const formatInvoiceNumber = (invoiceNumber: number) =>
  invoiceNumber.toString().padStart(4, "0");

// A sale line names the product and quantity; the batch is optional — when it
// is omitted the store draws stock from open batches, earliest expiry first.
export const CreateInvoiceLineInput = Schema.Struct({
  productId: Schema.String,
  batchId: Schema.NullOr(Schema.String),
  quantity: Schema.Number,
  quantityType: Schema.Literals(["unit", "pack"]),
  salePrice: Schema.Number,
});
export type CreateInvoiceLineInput = typeof CreateInvoiceLineInput.Type;

export const CreateInvoiceInput = Schema.Struct({
  customerName: Schema.NullOr(Schema.String),
  items: Schema.Array(CreateInvoiceLineInput),
});
export type CreateInvoiceInput = typeof CreateInvoiceInput.Type;

export const InvoiceIdInput = Schema.Struct({ id: Schema.String });
export type InvoiceIdInput = typeof InvoiceIdInput.Type;

const stockMovementRow = createSelectSchema(stockMovements);
export const StockMovement = Schema.Struct(stockMovementRow.fields);
export type StockMovement = typeof StockMovement.Type;
